// ============================================================
// MOCK DATA — replace with real API calls in production
// ============================================================

export const CATEGORIES = [
  'All', 'Programming', 'Data Science', 'Web Development',
  'Cloud Computing', 'UI/UX Design', 'Digital Marketing', 'DevOps',
];

export const COURSES = [
  {
    id: 1,
    title: 'Complete Python Bootcamp: From Zero to Hero in Python',
    instructor: 'Dr. Angela Yu',
    instructorBio: 'Senior Developer & Lead Instructor at London App Brewery with 10+ years experience.',
    category: 'Programming',
    price: 1999,
    originalPrice: 4999,
    rating: 4.8,
    reviews: 12480,
    students: 84320,
    duration: '22h 15m',
    level: 'Beginner',
    thumbnail: '🐍',
    color: '#1a3a5c',
    lessons: 185,
    description: 'Learn Python like a professional! Start from the basics and go all the way to creating your own applications and games. This course covers Python 3 with over 100 exercises and projects.',
    outcomes: [
      'Program in Python professionally',
      'Build real-world Python applications',
      'Learn Object-Oriented Programming',
      'Create web scrapers & automation scripts',
      'Understand Python data structures',
      'Work with APIs and JSON data',
    ],
    curriculum: [
      { title: 'Introduction & Setup', lessons: ['Welcome & Course Overview', 'Setting Up Python', 'Using Replit IDE', 'Hello World'] },
      { title: 'Python Basics', lessons: ['Variables & Data Types', 'String Manipulation', 'Input & Print', 'Type Conversion'] },
      { title: 'Control Flow', lessons: ['If/Else Statements', 'Loops: For & While', 'Functions', 'Scope & Local/Global'] },
      { title: 'Object-Oriented Python', lessons: ['Classes & Objects', 'Inheritance', 'Polymorphism', 'Special Methods'] },
      { title: 'Projects', lessons: ['Calculator App', 'Password Generator', 'Hangman Game', 'Final Capstone'] },
    ],
    enrolled: true,
    progress: 65,
    tags: ['Python', 'Programming', 'OOP', 'Automation'],
  },
  {
    id: 2,
    title: 'Machine Learning A–Z: AI, Python & R in Data Science',
    instructor: 'Kirill Eremenko',
    instructorBio: 'Data Scientist with 6+ years experience consulting for Fortune 500 companies.',
    category: 'Data Science',
    price: 2499,
    originalPrice: 5999,
    rating: 4.7,
    reviews: 9840,
    students: 62100,
    duration: '40h 30m',
    level: 'Intermediate',
    thumbnail: '🤖',
    color: '#1a2f4a',
    lessons: 320,
    description: 'Master Machine Learning on Python & R. Have a great intuition of many Machine Learning models. Handle specific topics like Reinforcement Learning, NLP, and Deep Learning.',
    outcomes: ['Supervised & Unsupervised ML', 'Feature Engineering', 'Neural Networks & Deep Learning', 'Model evaluation & tuning', 'Reinforcement Learning basics', 'NLP fundamentals'],
    curriculum: [
      { title: 'Data Preprocessing', lessons: ['Importing Libraries', 'Importing the Dataset', 'Handling Missing Data', 'Encoding Variables'] },
      { title: 'Regression', lessons: ['Simple Linear Regression', 'Multiple Linear Regression', 'Polynomial Regression', 'Random Forest Regression'] },
      { title: 'Classification', lessons: ['Logistic Regression', 'K-NN', 'SVM', 'Decision Trees'] },
      { title: 'Deep Learning', lessons: ['Artificial Neural Networks', 'Convolutional Neural Networks', 'Recurrent Neural Networks', 'Self-Organizing Maps'] },
    ],
    enrolled: true,
    progress: 28,
    tags: ['ML', 'AI', 'Python', 'R', 'Data Science'],
  },
  {
    id: 3,
    title: 'The Complete Web Developer: Zero to Mastery 2024',
    instructor: 'Andrei Neagoie',
    instructorBio: 'Senior Software Engineer with experience at top tech companies. Trained 500K+ developers.',
    category: 'Web Development',
    price: 1799,
    originalPrice: 3999,
    rating: 4.9,
    reviews: 18200,
    students: 108000,
    duration: '35h',
    level: 'Beginner',
    thumbnail: '🌐',
    color: '#0F3A3A',
    lessons: 290,
    description: 'Learn to code and become a Full Stack Web Developer in 2024 with HTML, CSS, JavaScript, React, Node.js, MongoDB, and more! Includes 20+ real projects.',
    outcomes: ['HTML5 & CSS3 mastery', 'JavaScript ES6+', 'React.js & Redux', 'Node.js & Express', 'MongoDB & SQL', 'RESTful APIs'],
    curriculum: [
      { title: 'Web Fundamentals', lessons: ['HTML Basics', 'CSS Selectors', 'Flexbox & Grid', 'Responsive Design'] },
      { title: 'JavaScript', lessons: ['JS Fundamentals', 'DOM Manipulation', 'Async/Await', 'Fetch API'] },
      { title: 'React', lessons: ['Components & Props', 'State & Hooks', 'Redux Toolkit', 'React Router'] },
      { title: 'Backend', lessons: ['Node & Express', 'REST APIs', 'MongoDB', 'Authentication'] },
    ],
    enrolled: false,
    progress: 0,
    tags: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
  },
  {
    id: 4,
    title: 'AWS Certified Solutions Architect – Associate 2024',
    instructor: 'Neal Davis',
    instructorBio: 'AWS certified professional with 15 years of cloud architecture experience.',
    category: 'Cloud Computing',
    price: 2999,
    originalPrice: 6999,
    rating: 4.6,
    reviews: 7300,
    students: 45200,
    duration: '28h',
    level: 'Advanced',
    thumbnail: '☁️',
    color: '#1a1a3a',
    lessons: 210,
    description: 'Pass the AWS Certified Solutions Architect Associate exam. Complete course with practice tests, hands-on labs, and real-world architecture patterns.',
    outcomes: ['AWS core services', 'Architecture best practices', 'Security & IAM', 'Cost optimization', 'High availability design', 'Practice exam questions'],
    curriculum: [
      { title: 'AWS Fundamentals', lessons: ['IAM', 'EC2', 'S3', 'VPC'] },
      { title: 'Databases', lessons: ['RDS', 'DynamoDB', 'ElastiCache', 'Redshift'] },
      { title: 'Serverless', lessons: ['Lambda', 'API Gateway', 'SQS & SNS', 'Step Functions'] },
      { title: 'Security', lessons: ['KMS', 'CloudTrail', 'WAF & Shield', 'Cognito'] },
    ],
    enrolled: false,
    progress: 0,
    tags: ['AWS', 'Cloud', 'Architecture', 'DevOps'],
  },
  {
    id: 5,
    title: 'UI/UX Design Bootcamp: Figma to Production 2024',
    instructor: 'Sarah Chen',
    instructorBio: 'Senior Product Designer at Meta with 8 years of design leadership experience.',
    category: 'UI/UX Design',
    price: 1599,
    originalPrice: 3499,
    rating: 4.8,
    reviews: 5600,
    students: 31400,
    duration: '18h',
    level: 'Beginner',
    thumbnail: '🎨',
    color: '#3A1a3A',
    lessons: 145,
    description: 'Master UI/UX design from scratch. Learn Figma, user research, design systems, and build a professional portfolio with real-world projects.',
    outcomes: ['Figma mastery', 'User research methods', 'Design systems & tokens', 'Prototyping & testing', 'Mobile-first design', 'Portfolio projects'],
    curriculum: [
      { title: 'Design Fundamentals', lessons: ['Design Principles', 'Color Theory', 'Typography', 'Grid Systems'] },
      { title: 'Figma Mastery', lessons: ['Interface Tour', 'Components', 'Auto Layout', 'Prototyping'] },
      { title: 'UX Research', lessons: ['User Interviews', 'Affinity Mapping', 'User Journeys', 'Usability Testing'] },
      { title: 'Capstone', lessons: ['Mobile App Design', 'Web App Design', 'Handoff to Dev', 'Portfolio Review'] },
    ],
    enrolled: false,
    progress: 0,
    tags: ['Figma', 'UX', 'Design', 'Prototyping'],
  },
  {
    id: 6,
    title: 'React & Next.js: The Complete Guide 2024',
    instructor: 'Maximilian Schwarzmüller',
    instructorBio: 'Udemy Instructor of the Year. 2.5M+ students across 50+ courses worldwide.',
    category: 'Web Development',
    price: 2199,
    originalPrice: 4999,
    rating: 4.8,
    reviews: 21000,
    students: 135000,
    duration: '48h',
    level: 'Intermediate',
    thumbnail: '⚛️',
    color: '#0F1B2D',
    lessons: 380,
    description: 'Dive in and learn React.js from scratch! Learn Reactjs, Redux, React Hooks, React Router, Next.js and way more with this complete course.',
    outcomes: ['React fundamentals & JSX', 'Hooks & Context API', 'Redux Toolkit', 'Next.js SSR/SSG', 'API Routes', 'Deployment strategies'],
    curriculum: [
      { title: 'React Basics', lessons: ['JSX & Components', 'Props & State', 'Event Handling', 'Conditional Rendering'] },
      { title: 'Advanced React', lessons: ['useEffect & Side Effects', 'Custom Hooks', 'Context API', 'useReducer'] },
      { title: 'Next.js', lessons: ['Pages & Routing', 'Data Fetching', 'API Routes', 'Middleware'] },
      { title: 'State Management', lessons: ['Redux Toolkit', 'RTK Query', 'Zustand', 'Jotai'] },
    ],
    enrolled: false,
    progress: 0,
    tags: ['React', 'Next.js', 'Redux', 'JavaScript'],
  },
  {
    id: 7,
    title: 'Digital Marketing Masterclass 2024',
    instructor: 'Phil Ebiner',
    instructorBio: 'Award-winning digital marketer and course creator with 1M+ students.',
    category: 'Digital Marketing',
    price: 1299,
    originalPrice: 2999,
    rating: 4.5,
    reviews: 8900,
    students: 58700,
    duration: '23h',
    level: 'Beginner',
    thumbnail: '📈',
    color: '#1a3a1a',
    lessons: 180,
    description: 'Become a digital marketing expert! SEO, Social Media Marketing, Email Marketing, YouTube, Facebook Ads, Google Analytics & more.',
    outcomes: ['SEO & keyword strategy', 'Social media marketing', 'Email campaigns', 'Google & Facebook Ads', 'Content marketing', 'Analytics & reporting'],
    curriculum: [
      { title: 'SEO Fundamentals', lessons: ['Keyword Research', 'On-Page SEO', 'Link Building', 'Technical SEO'] },
      { title: 'Social Media', lessons: ['Facebook Marketing', 'Instagram Strategy', 'LinkedIn B2B', 'TikTok Growth'] },
      { title: 'Paid Advertising', lessons: ['Google Ads', 'Facebook Ads', 'Retargeting', 'Budget Management'] },
      { title: 'Analytics', lessons: ['GA4 Setup', 'Conversion Tracking', 'A/B Testing', 'Reporting'] },
    ],
    enrolled: false,
    progress: 0,
    tags: ['SEO', 'Social Media', 'Ads', 'Marketing'],
  },
  {
    id: 8,
    title: 'Complete SQL: Database Design & Querying Mastery',
    instructor: 'Mosh Hamedani',
    instructorBio: 'Software engineer, author, and online instructor passionate about simplifying programming.',
    category: 'Data Science',
    price: 1499,
    originalPrice: 3499,
    rating: 4.7,
    reviews: 11200,
    students: 72000,
    duration: '15h',
    level: 'Beginner',
    thumbnail: '🗄️',
    color: '#2D1B0F',
    lessons: 120,
    description: 'A comprehensive SQL course for beginners and intermediate developers. Learn MySQL, PostgreSQL, database design, and performance tuning.',
    outcomes: ['SQL fundamentals', 'Complex joins & subqueries', 'Database design & normalization', 'Stored procedures & triggers', 'Performance optimization', 'PostgreSQL & MySQL'],
    curriculum: [
      { title: 'SQL Basics', lessons: ['SELECT Queries', 'WHERE Clauses', 'ORDER BY & LIMIT', 'Aggregation'] },
      { title: 'Joins', lessons: ['INNER JOIN', 'LEFT/RIGHT JOIN', 'Self Joins', 'Cross Joins'] },
      { title: 'Database Design', lessons: ['Normalization', 'Primary & Foreign Keys', 'Indexes', 'Transactions'] },
      { title: 'Advanced SQL', lessons: ['Stored Procedures', 'Views', 'Triggers', 'Performance Tuning'] },
    ],
    enrolled: false,
    progress: 0,
    tags: ['SQL', 'MySQL', 'PostgreSQL', 'Database'],
  },
];

export const TESTIMONIALS = [
  { id: 1, name: 'Arjun Mehta', role: 'Software Engineer @ Google', avatar: 'AM', text: 'LearnHub completely transformed my career. The Python and ML courses are world-class. I landed my dream job at Google within 4 months of completing the program!' },
  { id: 2, name: 'Priya Sharma', role: 'Full Stack Developer', avatar: 'PS', text: 'The instructors are phenomenal and the content is always up to date. I went from zero coding knowledge to building production apps. The community support is incredible.' },
  { id: 3, name: 'Rahul Verma', role: 'Data Analyst @ Amazon', avatar: 'RV', text: 'The structured learning paths and project-based approach make complex topics digestible. Best investment in my career. Would recommend to anyone serious about upskilling.' },
];

export const WHY_CHOOSE_US = [
  { icon: '🎯', title: 'Expert Instructors', desc: 'Learn from industry professionals with real-world experience at top companies.' },
  { icon: '📱', title: 'Learn Anywhere', desc: 'Access all courses on any device — desktop, tablet, or mobile — anytime.' },
  { icon: '🏆', title: 'Certificates', desc: 'Earn industry-recognized certificates to boost your career and LinkedIn profile.' },
  { icon: '💬', title: 'Community', desc: 'Join 135K+ learners in our active Slack community for peer support and networking.' },
  { icon: '♾️', title: 'Lifetime Access', desc: 'Purchase once and get lifetime access including all future course updates.' },
  { icon: '🔄', title: 'Money-Back Guarantee', desc: '30-day no-questions-asked refund if you are not satisfied with the course.' },
];

export const MOCK_USERS = [
  { id: 1, name: 'Arjun Mehta', email: 'arjun.m@gmail.com', courses: 5, joinedDate: 'Jan 12, 2024', status: 'active', avatar: 'AM', role: 'student' },
  { id: 2, name: 'Priya Sharma', email: 'priya.s@outlook.com', courses: 3, joinedDate: 'Feb 3, 2024', status: 'active', avatar: 'PS', role: 'student' },
  { id: 3, name: 'Rahul Singh', email: 'rahul.singh@yahoo.com', courses: 8, joinedDate: 'Nov 28, 2023', status: 'blocked', avatar: 'RS', role: 'student' },
  { id: 4, name: 'Kavya Nair', email: 'kavya.n@gmail.com', courses: 2, joinedDate: 'Mar 17, 2024', status: 'active', avatar: 'KN', role: 'student' },
  { id: 5, name: 'Vikram Patel', email: 'vikram.p@hotmail.com', courses: 11, joinedDate: 'Sep 5, 2023', status: 'active', avatar: 'VP', role: 'student' },
  { id: 6, name: 'Ananya Reddy', email: 'ananya.r@gmail.com', courses: 1, joinedDate: 'Apr 22, 2024', status: 'active', avatar: 'AR', role: 'student' },
  { id: 7, name: 'Sanjay Kumar', email: 'sanjay.k@company.com', courses: 4, joinedDate: 'Dec 1, 2023', status: 'active', avatar: 'SK', role: 'student' },
  { id: 8, name: 'Deepika Rao', email: 'deepika.r@gmail.com', courses: 6, joinedDate: 'Jan 30, 2024', status: 'active', avatar: 'DR', role: 'student' },
];

export const ANALYTICS_DATA = {
  userGrowth: [
    { month: 'Jan', users: 1200 }, { month: 'Feb', users: 1800 },
    { month: 'Mar', users: 2400 }, { month: 'Apr', users: 3100 },
    { month: 'May', users: 4200 }, { month: 'Jun', users: 5800 },
    { month: 'Jul', users: 7100 }, { month: 'Aug', users: 8900 },
  ],
  enrollments: [
    { month: 'Jan', enrollments: 340 }, { month: 'Feb', enrollments: 520 },
    { month: 'Mar', enrollments: 610 }, { month: 'Apr', enrollments: 780 },
    { month: 'May', enrollments: 1020 }, { month: 'Jun', enrollments: 1280 },
    { month: 'Jul', enrollments: 1560 }, { month: 'Aug', enrollments: 1890 },
  ],
  revenue: [
    { month: 'Jan', revenue: 145000 }, { month: 'Feb', revenue: 218000 },
    { month: 'Mar', revenue: 289000 }, { month: 'Apr', revenue: 371000 },
    { month: 'May', revenue: 482000 }, { month: 'Jun', revenue: 598000 },
    { month: 'Jul', revenue: 724000 }, { month: 'Aug', revenue: 892000 },
  ],
  popularCourses: [
    { name: 'React & Next.js', students: 135000 },
    { name: 'Python Bootcamp', students: 84320 },
    { name: 'SQL Mastery', students: 72000 },
    { name: 'ML A-Z', students: 62100 },
    { name: 'AWS Architect', students: 45200 },
  ],
  categoryBreakdown: [
    { name: 'Programming', value: 32 },
    { name: 'Web Dev', value: 28 },
    { name: 'Data Science', value: 20 },
    { name: 'Design', value: 10 },
    { name: 'Cloud', value: 10 },
  ],
};
